Update main.yml
edit workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,12 +27,19 @@ jobs:
         pip install -r requirement.txt
         pip install jupyter
 
+    - name: Debug:List all files in repo
+      run: |
+        ls -R  # List all files recursively to ensure files are in the correct locations
+
+    - name: Debug:List installed Python packages
+      run: pip list
+
     - name: Run Jupyter Notebook tests
       run: |
         jupyter nbconvert --to script notebooks/jup.ipynb
-        python notebooks/jup.py || exit 1
+        python notebooks/jup.py || exit 1  # Exit with error if notebook script fails
 
-    - name: Run Streamlit app
+    - name: Run Streamlit app (optional)
       run: |
         streamlit run scripts/app.py --server.headless true
       env:
